export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const GET_NEW_RELEASES = 'GET_NEW_RELEASES';
export const GET_CURRENT_ALBUM = 'GET_CURRENT_ALBUM';
export const GET_SEARCHED_RESULT = 'GET_SEARCHED_RESULT';