export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const GET_NEW_RELEASES = 'GET_NEW_RELEASES';
export const GET_CURRENT_ALBUM = 'GET_CURRENT_ALBUM';
export const GET_SEARCHED_RESULT = 'GET_SEARCHED_RESULT';
export const GET_NEW_PLAYLISTS = 'GET_NEW_PLAYLISTS';
export const GET_PLAYLIST_TRACKS = 'GET_PLAYLIST_TRACKS';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';